//! Mock data, mirroring `src/lib/data/mock.ts` so the API returns exactly the
//! shapes the UI already renders. Phase 1 ONLY: this is static demo data, not
//! real server state. The scenario matches the UI: high RAM pressure, Home in
//! Resource Standby, a blocked travel request.

use serde_json::json;

use crate::models::domain::*;

pub fn resources() -> ResourceSample {
    ResourceSample {
        ram_used_gb: 26.8,
        ram_total_gb: 32.0,
        cpu_pct: 71,
        swap_used_gb: 1.9,
        swap_total_gb: 8.0,
        disk_used_gb: 412.0,
        disk_total_gb: 930.0,
        ark_proc_mem_gb: 23.1,
    }
}

pub fn players() -> Vec<Player> {
    vec![
        Player {
            name: "Marcel".into(),
            level: 104,
            tribe: "Apex".into(),
            connected_mins: 142,
            map: "Ragnarok".into(),
        },
        Player {
            name: "Nyx".into(),
            level: 98,
            tribe: "Apex".into(),
            connected_mins: 96,
            map: "Ragnarok".into(),
        },
        Player {
            name: "Voidwalker".into(),
            level: 87,
            tribe: "Drakes".into(),
            connected_mins: 51,
            map: "Ragnarok".into(),
        },
        Player {
            name: "Sable".into(),
            level: 76,
            tribe: "Drakes".into(),
            connected_mins: 33,
            map: "Aberration".into(),
        },
        Player {
            name: "Korin".into(),
            level: 112,
            tribe: "Apex".into(),
            connected_mins: 210,
            map: "Aberration".into(),
        },
    ]
}

#[allow(clippy::too_many_arguments)]
fn cfg(
    unit: &str,
    ark: &str,
    q: u16,
    r: u16,
    g: u16,
    prio: i32,
    auto: bool,
    home: bool,
    autostop: bool,
    standby: bool,
    mods: &[&str],
) -> MapConfigSummary {
    MapConfigSummary {
        systemd_unit: unit.into(),
        ark_map_name: ark.into(),
        query_port: q,
        rcon_port: r,
        game_port: g,
        slot_priority: prio,
        auto_shutdown_enabled: auto,
        can_be_home: home,
        can_auto_stop_when_empty: autostop,
        can_enter_standby: standby,
        mod_list: mods.iter().map(|s| s.to_string()).collect(),
    }
}

pub fn maps() -> Vec<ArkMap> {
    vec![
        ArkMap {
            id: "home-island".into(),
            name: "The Island".into(),
            alias: "island".into(),
            role: "Home-capable".into(),
            assignment: "Home".into(),
            state: "Resource Standby".into(),
            players: 0,
            max_players: 20,
            ram_mb: 0,
            ram_estimate_mb: 7200,
            uptime_mins: 0,
            idle_mins: 18,
            last_backup: "2026-06-03 18:42".into(),
            rcon: "Disconnected".into(),
            systemd: "inactive (dead)".into(),
            restart_required: false,
            cpu_pct: 0,
            save_size_mb: 184,
            is_home: true,
            protected: true,
            next_action: "Auto-restart when resources recover or Home requested".into(),
            config: cfg(
                "ark-server@home-island.service",
                "TheIsland",
                27015,
                27020,
                7777,
                0,
                false,
                true,
                false,
                true,
                &[
                    "Structures Plus (S+)",
                    "Awesome SpyGlass!",
                    "Dino Storage v2",
                    "Super Structures",
                ],
            ),
        },
        ArkMap {
            id: "travel-rag".into(),
            name: "Ragnarok".into(),
            alias: "ragnarok".into(),
            role: "Travel-capable".into(),
            assignment: "Travel A".into(),
            state: "Online".into(),
            players: 3,
            max_players: 20,
            ram_mb: 8100,
            ram_estimate_mb: 8000,
            uptime_mins: 148,
            idle_mins: 0,
            last_backup: "2026-06-03 20:30".into(),
            rcon: "Connected".into(),
            systemd: "active (running)".into(),
            restart_required: false,
            cpu_pct: 38,
            save_size_mb: 221,
            is_home: false,
            protected: false,
            next_action: "Monitoring players — auto-shutdown only when empty".into(),
            config: cfg(
                "ark-server@travel-a.service",
                "Ragnarok",
                27017,
                27022,
                7779,
                1,
                true,
                false,
                true,
                false,
                &[
                    "Structures Plus (S+)",
                    "Awesome SpyGlass!",
                    "Dino Storage v2",
                ],
            ),
        },
        ArkMap {
            id: "travel-ab".into(),
            name: "Aberration".into(),
            alias: "aberration".into(),
            role: "Travel-capable".into(),
            assignment: "Travel B".into(),
            state: "Online".into(),
            players: 2,
            max_players: 20,
            ram_mb: 7600,
            ram_estimate_mb: 7800,
            uptime_mins: 64,
            idle_mins: 0,
            last_backup: "2026-06-03 19:58".into(),
            rcon: "Connected".into(),
            systemd: "active (running)".into(),
            restart_required: true,
            cpu_pct: 33,
            save_size_mb: 167,
            is_home: false,
            protected: false,
            next_action: "Restart required — GameUserSettings.ini changed".into(),
            config: cfg(
                "ark-server@travel-b.service",
                "Aberration",
                27019,
                27024,
                7781,
                2,
                true,
                false,
                true,
                false,
                &[
                    "Awesome SpyGlass!",
                    "Dino Storage v2",
                    "Aberration Ascended Loot",
                ],
            ),
        },
        ArkMap {
            id: "map-extinction".into(),
            name: "Extinction".into(),
            alias: "extinction".into(),
            role: "Travel-capable".into(),
            assignment: "Unassigned".into(),
            state: "Offline".into(),
            players: 0,
            max_players: 20,
            ram_mb: 0,
            ram_estimate_mb: 8200,
            uptime_mins: 0,
            idle_mins: 0,
            last_backup: "2026-06-02 23:10".into(),
            rcon: "Disconnected".into(),
            systemd: "inactive (dead)".into(),
            restart_required: false,
            cpu_pct: 0,
            save_size_mb: 203,
            is_home: false,
            protected: false,
            next_action: "Idle — start via !travel extinction".into(),
            config: cfg(
                "ark-server@travel-c.service",
                "Extinction",
                27021,
                27026,
                7783,
                3,
                true,
                false,
                true,
                false,
                &["Awesome SpyGlass!", "Dino Storage v2"],
            ),
        },
        ArkMap {
            id: "map-scorched".into(),
            name: "Scorched Earth".into(),
            alias: "scorched".into(),
            role: "Travel-capable".into(),
            assignment: "Unassigned".into(),
            state: "Offline".into(),
            players: 0,
            max_players: 20,
            ram_mb: 0,
            ram_estimate_mb: 6800,
            uptime_mins: 0,
            idle_mins: 0,
            last_backup: "2026-06-01 14:05".into(),
            rcon: "Disconnected".into(),
            systemd: "inactive (dead)".into(),
            restart_required: false,
            cpu_pct: 0,
            save_size_mb: 142,
            is_home: false,
            protected: false,
            next_action: "Idle — start via !travel scorched".into(),
            config: cfg(
                "ark-server@travel-d.service",
                "ScorchedEarth_P",
                27023,
                27028,
                7785,
                4,
                true,
                false,
                true,
                false,
                &["Awesome SpyGlass!"],
            ),
        },
        ArkMap {
            id: "map-fjordur".into(),
            name: "Fjordur".into(),
            alias: "fjordur".into(),
            role: "Home-capable".into(),
            assignment: "Unassigned".into(),
            state: "Offline".into(),
            players: 0,
            max_players: 20,
            ram_mb: 0,
            ram_estimate_mb: 8600,
            uptime_mins: 0,
            idle_mins: 0,
            last_backup: "2026-05-30 09:21".into(),
            rcon: "Disconnected".into(),
            systemd: "inactive (dead)".into(),
            restart_required: false,
            cpu_pct: 0,
            save_size_mb: 256,
            is_home: false,
            protected: false,
            next_action: "Idle — Home-capable alternate".into(),
            config: cfg(
                "ark-server@travel-e.service",
                "Fjordur",
                27025,
                27030,
                7787,
                5,
                true,
                true,
                true,
                true,
                &[
                    "Structures Plus (S+)",
                    "Awesome SpyGlass!",
                    "Dino Storage v2",
                ],
            ),
        },
    ]
}

pub fn active_travel() -> TravelRequest {
    TravelRequest {
        id: "tr-2201".into(),
        map: "Extinction".into(),
        requested_by: "Sable".into(),
        source: "In-game chat".into(),
        source_raw: "!travel extinction".into(),
        source_map: "Aberration".into(),
        step: 2,
        result: "Blocked".into(),
        reason: "Both travel slots have active players. Request queued until a slot frees or Home leaves Resource Standby.".into(),
        at: "2026-06-03 20:48".into(),
    }
}

pub fn backups() -> Vec<Backup> {
    vec![
        Backup {
            id: "b1".into(),
            map: "Aberration".into(),
            kind: "save".into(),
            size_mb: 167,
            created: "2026-06-03 20:55".into(),
            reason: "scheduled".into(),
            status: "running".into(),
            progress: Some(62),
            error: None,
        },
        Backup {
            id: "b2".into(),
            map: "The Island".into(),
            kind: "save".into(),
            size_mb: 184,
            created: "2026-06-03 20:40".into(),
            reason: "resource standby".into(),
            status: "success".into(),
            progress: None,
            error: None,
        },
        Backup {
            id: "b3".into(),
            map: "Ragnarok".into(),
            kind: "save".into(),
            size_mb: 221,
            created: "2026-06-03 20:30".into(),
            reason: "scheduled".into(),
            status: "success".into(),
            progress: None,
            error: None,
        },
        Backup {
            id: "b4".into(),
            map: "Aberration".into(),
            kind: "config".into(),
            size_mb: 1,
            created: "2026-06-03 19:58".into(),
            reason: "pre-config-change".into(),
            status: "success".into(),
            progress: None,
            error: None,
        },
        Backup {
            id: "b5".into(),
            map: "Cluster".into(),
            kind: "cluster data".into(),
            size_mb: 64,
            created: "2026-06-03 12:00".into(),
            reason: "scheduled".into(),
            status: "verifying".into(),
            progress: Some(88),
            error: None,
        },
        Backup {
            id: "b6".into(),
            map: "Extinction".into(),
            kind: "save".into(),
            size_mb: 0,
            created: "2026-06-02 23:10".into(),
            reason: "auto-shutdown".into(),
            status: "failed".into(),
            progress: None,
            error: Some("rsync exited 23: disk write timeout on /srv/ark/backups".into()),
        },
        Backup {
            id: "b7".into(),
            map: "The Island".into(),
            kind: "mod".into(),
            size_mb: 12,
            created: "2026-06-02 09:30".into(),
            reason: "pre-mod-change".into(),
            status: "success".into(),
            progress: None,
            error: None,
        },
    ]
}

pub fn mods() -> Vec<Mod> {
    vec![
        Mod {
            id: "m1".into(),
            name: "Structures Plus (S+)".into(),
            workshop_id: "731604991".into(),
            enabled: true,
            installed: true,
            load_order: 1,
            last_updated: "2026-05-28".into(),
            size_mb: 142,
            used_by: vec!["The Island".into(), "Ragnarok".into(), "Fjordur".into()],
            state: "active".into(),
            progress: None,
        },
        Mod {
            id: "m2".into(),
            name: "Awesome SpyGlass!".into(),
            workshop_id: "1404697612".into(),
            enabled: true,
            installed: true,
            load_order: 2,
            last_updated: "2026-05-20".into(),
            size_mb: 38,
            used_by: vec![
                "The Island".into(),
                "Ragnarok".into(),
                "Aberration".into(),
                "Extinction".into(),
            ],
            state: "active".into(),
            progress: None,
        },
        Mod {
            id: "m3".into(),
            name: "Dino Storage v2".into(),
            workshop_id: "1609138312".into(),
            enabled: true,
            installed: true,
            load_order: 3,
            last_updated: "2026-05-31".into(),
            size_mb: 56,
            used_by: vec!["The Island".into(), "Ragnarok".into(), "Aberration".into()],
            state: "active".into(),
            progress: None,
        },
        Mod {
            id: "m4".into(),
            name: "Super Structures".into(),
            workshop_id: "1999447172".into(),
            enabled: false,
            installed: true,
            load_order: 0,
            last_updated: "2026-04-12".into(),
            size_mb: 121,
            used_by: vec!["The Island".into()],
            state: "disabled".into(),
            progress: None,
        },
        Mod {
            id: "m5".into(),
            name: "Ultra Stacks".into(),
            workshop_id: "1654255131".into(),
            enabled: false,
            installed: true,
            load_order: 0,
            last_updated: "2026-03-02".into(),
            size_mb: 8,
            used_by: vec![],
            state: "disabled".into(),
            progress: None,
        },
        Mod {
            id: "m6".into(),
            name: "Aberration Ascended Loot".into(),
            workshop_id: "2901112233".into(),
            enabled: true,
            installed: false,
            load_order: 4,
            last_updated: "—".into(),
            size_mb: 0,
            used_by: vec!["Aberration".into()],
            state: "downloading".into(),
            progress: Some(47),
        },
        Mod {
            id: "m7".into(),
            name: "Custom Ragnarok Expansion".into(),
            workshop_id: "3088112299".into(),
            enabled: true,
            installed: false,
            load_order: 0,
            last_updated: "2026-05-15".into(),
            size_mb: 0,
            used_by: vec!["Ragnarok".into()],
            state: "failed".into(),
            progress: None,
        },
        Mod {
            id: "m8".into(),
            name: "Legacy Bridge Mod".into(),
            workshop_id: "1230000099".into(),
            enabled: false,
            installed: false,
            load_order: 0,
            last_updated: "—".into(),
            size_mb: 0,
            used_by: vec![],
            state: "missing".into(),
            progress: None,
        },
    ]
}

pub fn config_fields() -> Vec<ConfigField> {
    let num = |key: &str,
               label: &str,
               v: f64,
               group: &str,
               min: f64,
               max: f64,
               step: f64,
               hint: &str,
               restart: bool| ConfigField {
        key: key.into(),
        label: label.into(),
        value: json!(v),
        kind: "number".into(),
        group: group.into(),
        min: Some(min),
        max: Some(max),
        step: Some(step),
        options: None,
        hint: hint.into(),
        restart_required: restart,
    };
    let boolean =
        |key: &str, label: &str, v: bool, group: &str, hint: &str, restart: bool| ConfigField {
            key: key.into(),
            label: label.into(),
            value: json!(v),
            kind: "bool".into(),
            group: group.into(),
            min: None,
            max: None,
            step: None,
            options: None,
            hint: hint.into(),
            restart_required: restart,
        };
    vec![
        num(
            "XPMultiplier",
            "XP Multiplier",
            3.0,
            "Rates",
            0.1,
            100.0,
            0.1,
            "Global experience gain rate",
            false,
        ),
        num(
            "HarvestAmountMultiplier",
            "Harvest Multiplier",
            4.0,
            "Rates",
            0.1,
            100.0,
            0.1,
            "Resource gathering yield",
            false,
        ),
        num(
            "TamingSpeedMultiplier",
            "Taming Speed",
            8.0,
            "Rates",
            0.1,
            100.0,
            0.1,
            "How fast dinos tame",
            false,
        ),
        num(
            "BabyMatureSpeedMultiplier",
            "Baby Mature Speed",
            12.0,
            "Breeding",
            0.1,
            100.0,
            0.1,
            "Baby growth rate",
            false,
        ),
        num(
            "MatingIntervalMultiplier",
            "Mating Interval",
            0.4,
            "Breeding",
            0.01,
            10.0,
            0.01,
            "Lower = breed more often",
            false,
        ),
        num(
            "EggHatchSpeedMultiplier",
            "Egg Hatch Speed",
            10.0,
            "Breeding",
            0.1,
            100.0,
            0.1,
            "Incubation speed",
            false,
        ),
        num(
            "PlayerWeightMultiplier",
            "Player Weight",
            2.0,
            "Stats",
            0.1,
            50.0,
            0.1,
            "Carry capacity for players",
            true,
        ),
        num(
            "DinoWeightMultiplier",
            "Dino Weight",
            3.0,
            "Stats",
            0.1,
            50.0,
            0.1,
            "Carry capacity for dinos",
            true,
        ),
        num(
            "DifficultyOffset",
            "Difficulty Offset",
            1.0,
            "World",
            0.0,
            1.0,
            0.01,
            "1.0 = max wild levels",
            true,
        ),
        num(
            "OverrideOfficialDifficulty",
            "Max Difficulty",
            5.0,
            "World",
            1.0,
            20.0,
            0.5,
            "Difficulty 5 = level 150 wilds",
            true,
        ),
        boolean(
            "ServerPVE",
            "PvE Mode",
            true,
            "World",
            "On = PvE, Off = PvP",
            true,
        ),
        boolean(
            "bAllowFlyerCarryPvE",
            "Allow Flyer Carry",
            true,
            "World",
            "Flyers can pick up dinos in PvE",
            true,
        ),
        num(
            "StructurePickupTimeAfterPlacement",
            "Structure Pickup Timer (s)",
            1800.0,
            "Structures",
            0.0,
            99999.0,
            30.0,
            "Quick-pickup window",
            false,
        ),
        num(
            "ItemStackSizeMultiplier",
            "Stack Size Multiplier",
            5.0,
            "Items",
            1.0,
            100.0,
            1.0,
            "Inventory stack scaling",
            true,
        ),
        num(
            "SPlusCraftingSpeed",
            "S+ Crafting Speed",
            4.0,
            "S+",
            0.1,
            50.0,
            0.1,
            "Structures Plus station crafting speed",
            false,
        ),
        num(
            "SPlusForgeSpeed",
            "S+ Forge Speed",
            3.0,
            "S+",
            0.1,
            50.0,
            0.1,
            "S+ forge smelt rate",
            false,
        ),
        num(
            "SPlusStorageBoost",
            "S+ Storage Boost",
            2.0,
            "S+",
            1.0,
            20.0,
            1.0,
            "S+ storage capacity multiplier",
            false,
        ),
    ]
}

pub const RAW_GAME_INI: &str = r#"[/script/shootergame.shootergamemode]
HarvestAmountMultiplier=4.0
TamingSpeedMultiplier=8.0
MatingIntervalMultiplier=0.4
BabyMatureSpeedMultiplier=12.0
EggHatchSpeedMultiplier=10.0
PlayerWeightMultiplier=2.0
DinoCharacterFoodDrainMultiplier=0.8
bAllowFlyerCarryPvE=True
ConfigOverrideItemMaxQuantity=(ItemClassString="PrimalItemResource_Wood_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))"#;

pub const RAW_GUS_INI: &str = r#"[ServerSettings]
ServerPVE=True
XPMultiplier=3.0
DifficultyOffset=1.0
OverrideOfficialDifficulty=5.0
AllowThirdPersonPlayer=True
ShowMapPlayerLocation=True
ServerCrosshair=True
RCONEnabled=True
RCONPort=27020
ItemStackSizeMultiplier=5.0

[/script/engine.gamesession]
MaxPlayers=20"#;

pub fn discord_commands() -> serde_json::Value {
    json!([
        { "cmd": "/status", "desc": "Cluster + map overview", "access": "Everyone" },
        { "cmd": "/maps", "desc": "List configured maps and state", "access": "Everyone" },
        { "cmd": "/players", "desc": "Who is online and where", "access": "Everyone" },
        { "cmd": "/travel <map>", "desc": "Request a travel server", "access": "Everyone" },
        { "cmd": "/mods", "desc": "Show active mod load order", "access": "Everyone" },
        { "cmd": "/config", "desc": "View config summary", "access": "Admin" },
        { "cmd": "/restart <map>", "desc": "Restart a map", "access": "Admin" },
        { "cmd": "/broadcast <msg>", "desc": "Send in-game broadcast", "access": "Admin" }
    ])
}

pub fn discord_events() -> Vec<DiscordEvent> {
    vec![
        DiscordEvent {
            id: "d1".into(),
            ts: "20:48".into(),
            kind: "travel".into(),
            text: "Sable requested /travel extinction — blocked (slots full)".into(),
        },
        DiscordEvent {
            id: "d2".into(),
            ts: "20:41".into(),
            kind: "alert".into(),
            text: "Resource warning sent: RAM pressure 84%".into(),
        },
        DiscordEvent {
            id: "d3".into(),
            ts: "20:40".into(),
            kind: "alert".into(),
            text: "Backup completed alert: The Island (resource standby)".into(),
        },
        DiscordEvent {
            id: "d4".into(),
            ts: "18:13".into(),
            kind: "status".into(),
            text: "Ragnarok readiness announced in #ark-status".into(),
        },
        DiscordEvent {
            id: "d5".into(),
            ts: "17:02".into(),
            kind: "status".into(),
            text: "Korin ran /status".into(),
        },
    ]
}

pub fn alert_settings() -> Vec<AlertSetting> {
    vec![
        AlertSetting {
            key: "started".into(),
            label: "Server started".into(),
            enabled: true,
        },
        AlertSetting {
            key: "stopped".into(),
            label: "Server stopped".into(),
            enabled: true,
        },
        AlertSetting {
            key: "pressure".into(),
            label: "Resource pressure".into(),
            enabled: true,
        },
        AlertSetting {
            key: "backupFailed".into(),
            label: "Backup failed".into(),
            enabled: true,
        },
        AlertSetting {
            key: "modUpdate".into(),
            label: "Mod update needed".into(),
            enabled: false,
        },
        AlertSetting {
            key: "rcon".into(),
            label: "RCON disconnected".into(),
            enabled: true,
        },
    ]
}

pub fn activity_log() -> Vec<LogEvent> {
    let e = |id: &str,
             ts: &str,
             sev: &str,
             src: &str,
             actor: &str,
             map: &str,
             msg: &str,
             detail: &str| LogEvent {
        id: id.into(),
        ts: ts.into(),
        severity: sev.into(),
        source: src.into(),
        actor: actor.into(),
        target_map: map.into(),
        message: msg.into(),
        detail: detail.into(),
    };
    vec![
        e("l1", "2026-06-03 20:48:11", "warn", "Travel", "Sable", "Extinction", "Travel request denied because both travel slots had active players", "Slots: Travel A=Ragnarok (3 players), Travel B=Aberration (2 players). Request queued."),
        e("l2", "2026-06-03 20:48:03", "info", "RCON", "rust-manager", "Aberration", "Travel request received on Aberration RCON", "Chat line: Sable: !travel extinction"),
        e("l3", "2026-06-03 20:41:55", "warn", "Governor", "resource-governor", "The Island", "Home entered Resource Standby because it was empty and RAM pressure was high", "RAM 84% > pressure threshold 82%. Home players=0. Travel maps active."),
        e("l4", "2026-06-03 20:40:20", "success", "Backup", "rust-manager", "The Island", "Backup completed for Home before Resource Standby", "save backup 184 MB -> /srv/ark/backups/home-island/2026-06-03T2040.tar.zst"),
        e("l5", "2026-06-03 19:58:40", "warn", "Config", "Marcel", "Aberration", "GameUserSettings.ini changed; restart required", "OverrideOfficialDifficulty 4.0 -> 5.0. Pre-config backup taken."),
        e("l6", "2026-06-03 19:30:02", "warn", "Mod", "Marcel", "The Island", "Mod disabled; restart required", "Super Structures (1999447172) removed from active load order, files kept."),
        e("l7", "2026-06-03 18:14:09", "success", "RCON", "rust-manager", "Travel B", "RCON reconnect succeeded for Travel B", "Reconnected after 2 retries (4.1s)."),
        e("l8", "2026-06-03 18:13:12", "info", "Discord", "discord-bot", "Ragnarok", "Discord user requested Extinction", "/travel extinction by Korin (queued earlier)."),
        e("l9", "2026-06-03 18:12:50", "success", "Map", "Voidwalker", "Ragnarok", "Ragnarok started by in-game command from Marcel", "systemd unit ark-server@travel-a.service started."),
        e("l10", "2026-06-03 18:12:48", "info", "Map", "systemd", "Ragnarok", "systemd unit ark-server@travel-a.service started", "Active: activating -> active (running) in 41s."),
        e("l11", "2026-06-03 17:02:31", "info", "User", "Marcel", "—", "Admin opened Config Editor", "Web UI session via Tailscale 100.84.x.x."),
        e("l12", "2026-06-02 23:10:18", "error", "Backup", "rust-manager", "Extinction", "Backup failed during auto-shutdown", "rsync exited 23: disk write timeout on /srv/ark/backups."),
    ]
}

pub fn recent_activity() -> Vec<LogEvent> {
    let e = |id: &str,
             ts: &str,
             sev: &str,
             src: &str,
             actor: &str,
             map: &str,
             msg: &str,
             detail: &str| LogEvent {
        id: id.into(),
        ts: ts.into(),
        severity: sev.into(),
        source: src.into(),
        actor: actor.into(),
        target_map: map.into(),
        message: msg.into(),
        detail: detail.into(),
    };
    vec![
        e(
            "a1",
            "20:48",
            "warn",
            "Travel",
            "Sable",
            "Extinction",
            "Travel request blocked because both travel slots had players",
            "Source: Aberration RCON chat `!travel extinction`. Queued.",
        ),
        e(
            "a2",
            "20:41",
            "warn",
            "Governor",
            "resource-governor",
            "The Island",
            "Home entered Resource Standby — empty and travel maps had active players",
            "RAM pressure 84% > 82% threshold. Home saved + backed up before stop.",
        ),
        e(
            "a3",
            "20:40",
            "success",
            "Backup",
            "rust-manager",
            "The Island",
            "Backup completed before shutdown",
            "save backup, 184 MB, reason: resource standby",
        ),
        e(
            "a4",
            "18:12",
            "success",
            "Map",
            "Voidwalker",
            "Ragnarok",
            "Ragnarok started from in-game `!travel ragnarok`",
            "Travel Slot A assigned. RCON ready in 41s.",
        ),
        e(
            "a5",
            "18:13",
            "info",
            "Discord",
            "discord-bot",
            "Ragnarok",
            "Discord bot announced server readiness",
            "#ark-status: Ragnarok is ready for transfer.",
        ),
    ]
}
